openapi: 3.0.0
info:
  title: "Admin Portal APIs"
  description: Admin API POC
  version: 1.0.1
x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
x-amazon-apigateway-request-validator: all
paths:

  /v1/manage-tenant-details:
    get:
      summary: Get all Tenant Profiles
      consumes:
        - application/json
      produces:
        - application/json
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: POST
        passthroughBehavior: WHEN_NO_MATCH
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ManageTenantProfileLambda.Arn}/invocations
        responses:
          default:
            statusCode: "200"
      security:
        - UserPool: []
    post:
      summary: Create Tenant Profile
      consumes:
        - application/json
      produces:
        - application/json
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: POST
        passthroughBehavior: WHEN_NO_MATCH
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ManageTenantProfileLambda.Arn}/invocations
        responses:
          default:
            statusCode: "200"
      security:
        - UserPool: []
    patch:
      summary: Patch Tenants Profile
      consumes:
        - application/json
      produces:
        - application/json
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: POST
        passthroughBehavior: WHEN_NO_MATCH
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ManageTenantProfileLambda.Arn}/invocations
        responses:
          default:
            statusCode: "200"
      security:
        - UserPool: []

  /v1/manage-tenant-domains:
    get:
      summary: Gets Domains Related Information
      consumes:
        - application/json
      produces:
        - application/json
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: POST
        passthroughBehavior: WHEN_NO_MATCH
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ManageTenantSubDomainsLambda.Arn}/invocations
        responses:
          default:
            statusCode: "200"
      security:
        - UserPool: []
    post:
      summary: Creates Tenant Domains
      consumes:
        - application/json
      produces:
        - application/json
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: POST
        passthroughBehavior: WHEN_NO_MATCH
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ManageTenantSubDomainsLambda.Arn}/invocations
        responses:
          default:
            statusCode: "200"
      security:
        - UserPool: []
    patch:
      summary: Updates to Tenant Domains
      consumes:
        - application/json
      produces:
        - application/json
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: POST
        passthroughBehavior: WHEN_NO_MATCH
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ManageTenantSubDomainsLambda.Arn}/invocations
        responses:
          default:
            statusCode: "200"
      security:
        - UserPool: []

  /v1/manage-tenant-stages:
    get:
      summary: Get all tenant stages
      consumes:
        - application/json
      produces:
        - application/json
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: POST
        passthroughBehavior: WHEN_NO_MATCH
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ManageTenantStagesLambda.Arn}/invocations
        responses:
          default:
            statusCode: "200"
      security:
        - UserPool: []
    post:
      summary: POST Stage Comments for a tenant
      consumes:
        - application/json
      produces:
        - application/json
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: POST
        passthroughBehavior: WHEN_NO_MATCH
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ManageTenantStagesLambda.Arn}/invocations
        responses:
          default:
            statusCode: "200"
      security:
        - UserPool: []

components:
  schemas:
    Adminrequestbody:
      description: Admin request body of POST API
      type: object
      properties:
        AdminInput1:
          type: string
          description: Admin description of input1
        AdminInput2:
          type: string
          description: Admin description of input2
    Adminresponse:
      description: Admin response of the API
      type: object
      properties:
        AdminRequiredField:
          type: string
          description: Admin description of AdminRequiredField
        field2:
          type: string
        field3:
          type: object
    errorbody:
      type: object
      properties:
        errorText:
          type: string

securityDefinitions:
  UserPool:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    x-amazon-apigateway-authtype: "cognito_user_pools"
    x-amazon-apigateway-authorizer:
      type: "cognito_user_pools"
      providerARNs:
        - Fn::Sub: ${CognitoUserPool}