openapi: 3.0.0
info:
  title: "Supplier Portal APIs"
  description: Supplier api poc
  version: 1.0.1
x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
x-amazon-apigateway-request-validator: all
paths:
  /v1/manage-supplier-branches:
    get:
      summary: Get Supplier Branches
      consumes:
        - application/json
      produces:
        - application/json
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: POST
        passthroughBehavior: WHEN_NO_MATCH
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ManageSupplierBranchesLambda.Arn}/invocations
        responses:
          default:
            statusCode: "200"
      security:
        - UserPool: []
    post:
      summary: Create Supplier Branch
      consumes:
        - application/json
      produces:
        - application/json
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: POST
        passthroughBehavior: WHEN_NO_MATCH
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ManageSupplierBranchesLambda.Arn}/invocations
        responses:
          default:
            statusCode: "200"
      security:
        - UserPool: []
    patch:
      summary: Update Supplier Branch
      consumes:
        - application/json
      produces:
        - application/json
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: POST
        passthroughBehavior: WHEN_NO_MATCH
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ManageSupplierBranchesLambda.Arn}/invocations
        responses:
          default:
            statusCode: "200"
      security:
        - UserPool: []
    delete:
      summary: Delete Supplier Branch
      consumes:
        - application/json
      produces:
        - application/json
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: POST
        passthroughBehavior: WHEN_NO_MATCH
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ManageSupplierBranchesLambda.Arn}/invocations
        responses:
          default:
            statusCode: "200"
      security:
        - UserPool: []      
  /v1/manage-supplier-cards:
    get:
      summary: Get Supplier Cards
      consumes:
        - application/json
      produces:
        - application/json
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: POST
        passthroughBehavior: WHEN_NO_MATCH
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ManageSupplierCardsLambda.Arn}/invocations
        responses:
          default:
            statusCode: "200"
      security:
        - UserPool: []
    post:
      summary: Create Supplier Cards
      consumes:
        - application/json
      produces:
        - application/json
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: POST
        passthroughBehavior: WHEN_NO_MATCH
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ManageSupplierCardsLambda.Arn}/invocations
        responses:
          default:
            statusCode: "200"
      security:
        - UserPool: []
    patch:
      summary: Update Supplier Cards
      consumes:
        - application/json
      produces:
        - application/json
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: POST
        passthroughBehavior: WHEN_NO_MATCH
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ManageSupplierCardsLambda.Arn}/invocations
        responses:
          default:
            statusCode: "200"
      security:
        - UserPool: []
    delete:
      summary: Delete Supplier Cards
      consumes:
        - application/json
      produces:
        - application/json
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: POST
        passthroughBehavior: WHEN_NO_MATCH
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ManageSupplierCardsLambda.Arn}/invocations
        responses:
          default:
            statusCode: "200"
      security:
        - UserPool: []   

components:
  schemas:
    Supplierrequestbody:
      description: Supplier request body of POST API
      type: object
      properties:
        SupplierInput1:
          type: string
          description: Supplier description of input1
        SupplierInput2:
          type: string
          description: Supplier description of input2
    Supplierresponse:
      description: Supplier response of the API
      type: object
      properties:
        SupplierRequiredField:
          type: string
          description: Supplier description of SupplierRequiredField
        field2:
          type: string
        field3:
          type: object
    errorbody:
      type: object
      properties:
        errorText:
          type: string
    

securityDefinitions:
  UserPool:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "cognito_user_pools"
      x-amazon-apigateway-authorizer: 
        type: "cognito_user_pools"
        providerARNs: 
          - 
            Fn::Sub: arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${SupplierProfileCognitoUserPool}

  